#!/usr/bin/env sh

clang \
    -target i386-pc-win32 \
    -march=pentium3 \
    -fuse-ld=nxdk-link-offset \
    -ffreestanding \
    -nostdlib \
    -I${NXDK_DIR}/lib \
    -I${NXDK_DIR}/lib/winapi \
    -I${NXDK_DIR}/lib/xboxrt/vcruntime \
    -fno-builtin \
    -DNXDK \
    "$@"
